#!/bin/bash
source scripts/functions.sh
#gcc -c -Q -O2 -ftree-vectorize --help=optimizers > o2f

#SH="bash"
SH="busybox ash"
#SH="dash"

echo -n -e "Ash:    \t"

SwitchTo performance

i=0 ; while [ $i -lt $RUNS ]; do
        #printf "."
        ProgressBar ${i} ${RUNS}
        i=$(($i+1))
        time -p ( $SH -c 'for i in $(seq 1 5000000);do [ 1 = 1 ];done' ) 2>> "${TIMING_FILE}"
	CheckReturnCode
done

SwitchTo ondemand
