#!/bin/bash
source scripts/functions.sh
FLAC="flac"
echo -n -e "Flac:   \t"

cd downloads/

if [ ! -f pts-trondheim-3.wav ] ; then
	wget http://www.phoronix-test-suite.com/benchmark-files/pts-trondheim-wav-3.tar.gz
	tar xf pts-trondheim-wav-3.tar.gz
	rm pts-trondheim-wav-3.tar.gz
	rm wav-license.txt
fi

SwitchTo performance

i=0 ; while [ $i -lt $RUNS ]; do
	#printf "."
	ProgressBar ${i} ${RUNS}
	i=$(($i+1))
	time -p (for j in {1..3};do $FLAC --totally-silent --best pts-trondheim-3.wav -f -c > /dev/null;CheckReturnCode;done) 2>> "${TIMING_FILE}"
	CheckReturnCode
done
cd ..
SwitchTo ondemand
