#!/bin/bash
source scripts/functions.sh
#export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libjemalloc.so.1"
#export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
#export LD_PRELOAD="/usr/lib/libjemalloc.so.2"
#export LD_PRELOAD="/usr/lib/libtcmalloc.so.4"
#export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"

#JOBS=$CORES
#export OMP_NUM_THREADS=2

JOBS=$THREADS
export OMP_NUM_THREADS=1


if which lmp >/dev/null; then
    LAMMPS="lmp"
else
    if which lammps >/dev/null; then
        LAMMPS="lammps"
    else
        if which lammps-daily >/dev/null; then
            LAMMPS="lammps-daily"
        fi
    fi
fi
RETURN=$(pwd)
cd downloads/
if [ ! -f Cu_u3.eam ] ; then
        wget https://raw.githubusercontent.com/CFDEMproject/LAMMPS/master/bench/Cu_u3.eam
fi


TMP2=$(mktemp -d)
echo -n -e "Lammps: \t"
#echo "Using binary" $(which $LAMMPS) "on" $JOBS "cores"
#echo "With LD_PRELOAD" $LD_PRELOAD

cp Cu_u3.eam ${TMP2}
cd ${TMP2}
cat > in.eam <<- EOF
units           metal
atom_style      atomic
lattice         fcc 3.615
region          box block 0 50 0 50 0 50 ##needs 12GB RAM (200^3), 2GB RAM (100^3x50), 500M RAM (50^3x100)
create_box      1 box
create_atoms    1 box
pair_style      eam
pair_coeff      1 1 Cu_u3.eam
velocity        all create 1600.0 376847 loop geom
neighbor        1.0 bin
neigh_modify    every 1 delay 5 check yes
fix             1 all nve
timestep        0.005
thermo          50
run             100
EOF

SwitchTo performance

i=0 ; while [ $i -lt $RUNS ]; do
	#printf "."
	ProgressBar ${i} ${RUNS}
	i=$(($i+1))
	time -p ( mpirun -n $JOBS --use-hwthread-cpus $LAMMPS -in in.eam ) &>> "${TIMING_FILE}" #-sf omp -pk omp 2
	CheckReturnCode
done
cd ${RETURN}
rm -rf ${TMP2}
unset LD_PRELOAD
unset OMP_NUM_THREAD
SwitchTo ondemand
